export const COMMENT_LIST_REQUEST = "COMMENT_LIST_REQUEST";
export const COMMENT_LIST_SUCCESS = "COMMENT_LIST_SUCCESS";
export const COMMENT_LIST_FAIL = "COMMENT_LIST_FAIL";

export const COMMENT_APPROVE_REQUEST = "COMMENT_APPROVE_REQUEST";
export const COMMENT_APPROVE_SUCCESS = "COMMENT_APPROVE_SUCCESS";
export const COMMENT_APPROVE_FAIL = "COMMENT_APPROVE_FAIL";

export const COMMENT_DELETE_REQUEST = "COMMENT_DELETE_REQUEST";
export const COMMENT_DELETE_SUCCESS = "COMMENT_DELETE_SUCCESS";
export const COMMENT_DELETE_FAIL = "COMMENT_DELETE_FAIL";

export const COMMENT_ADD_REQUEST = "COMMENT_ADD_REQUEST";
export const COMMENT_ADD_SUCCESS = "COMMENT_ADD_SUCCESS";
export const COMMENT_ADD_FAIL = "COMMENT_ADD_FAIL";

export const COMMENT_LIST_UNAPPROVED_SUCCESS =
  "COMMENT_LIST_UNAPPROVED_SUCCESS";
export const COMMENT_LIST_APPROVED_SUCCESS = "COMMENT_LIST_APPROVED_SUCCESS";

export const COMMENT_APPROVED_LIST_REQUEST = "COMMENT_APPROVED_LIST_REQUEST";
export const COMMENT_APPROVED_LIST_SUCCESS = "COMMENT_APPROVED_LIST_SUCCESS";
export const COMMENT_APPROVED_LIST_FAIL = "COMMENT_APPROVED_LIST_FAIL";

export const COMMENT_UPDATE_REQUEST = "COMMENT_UPDATE_REQUEST";
export const COMMENT_UPDATE_SUCCESS = "COMMENT_UPDATE_SUCCESS";
export const COMMENT_UPDATE_FAIL = "COMMENT_UPDATE_FAIL";
