export const GURME_DETAIL_REQUEST = "GURME_DETAIL_REQUEST";
export const GURME_DETAIL_SUCCESS = "GURME_DETAIL_SUCCESS";
export const GURME_DETAIL_FAIL = "GURME_DETAIL_FAIL";

export const GURME_DETAIL_UPDATE_REQUEST = "GURME_DETAIL_UPDATE_REQUEST";
export const GURME_DETAIL_UPDATE_SUCCESS = "GURME_DETAIL_UPDATE_SUCCESS";
export const GURME_DETAIL_UPDATE_FAIL = "GURME_DETAIL_UPDATE_FAIL";
