export const QUESTION_LIST_REQUEST = "QUESTION_LIST_REQUEST";
export const QUESTION_LIST_SUCCESS = "QUESTION_LIST_SUCCESS";
export const QUESTION_LIST_FAIL = "QUESTION_LIST_FAIL";

export const QUESTION_ADD_REQUEST = "QUESTION_ADD_REQUEST";
export const QUESTION_ADD_SUCCESS = "QUESTION_ADD_SUCCESS";
export const QUESTION_ADD_FAIL = "QUESTION_ADD_FAIL";

export const QUESTION_DELETE_REQUEST = "QUESTION_DELETE_REQUEST";
export const QUESTION_DELETE_SUCCESS = "QUESTION_DELETE_SUCCESS";
export const QUESTION_DELETE_FAIL = "QUESTION_DELETE_FAIL";

export const QUESTION_EDIT_REQUEST = "QUESTION_EDIT_REQUEST";
export const QUESTION_EDIT_SUCCESS = "QUESTION_EDIT_SUCCESS";
export const QUESTION_EDIT_FAIL = "QUESTION_EDIT_FAIL";

export const QUESTION_UPDATE_ORDER_SUCCESS = "QUESTION_UPDATE_ORDER_SUCCESS";
export const QUESTION_UPDATE_ORDER_FAIL = "QUESTION_UPDATE_ORDER_FAIL";
