export const REPLY_LIST_REQUEST = "REPLY_LIST_REQUEST";
export const REPLY_LIST_SUCCESS = "REPLY_LIST_SUCCESS";
export const REPLY_LIST_FAIL = "REPLY_LIST_FAIL";

export const REPLY_APPROVE_REQUEST = "REPLY_APPROVE_REQUEST";
export const REPLY_APPROVE_SUCCESS = "REPLY_APPROVE_SUCCESS";
export const REPLY_APPROVE_FAIL = "REPLY_APPROVE_FAIL";

export const REPLY_DELETE_REQUEST = "REPLY_DELETE_REQUEST";
export const REPLY_DELETE_SUCCESS = "REPLY_DELETE_SUCCESS";
export const REPLY_DELETE_FAIL = "REPLY_DELETE_FAIL";
