export const RESTAURANT_ADD_REQUEST = "RESTAURANT_ADD_REQUEST";
export const RESTAURANT_ADD_SUCCESS = "RESTAURANT_ADD_SUCCESS";
export const RESTAURANT_ADD_FAIL = "RESTAURANT_ADD_FAIL";

export const RESTAURANT_LIST_REQUEST = "RESTAURANT_LIST_REQUEST";
export const RESTAURANT_LIST_SUCCESS = "RESTAURANT_LIST_SUCCESS";
export const RESTAURANT_LIST_FAIL = "RESTAURANT_LIST_FAIL";

export const RESTAURANT_DELETE_REQUEST = "RESTAURANT_DELETE_REQUEST";
export const RESTAURANT_DELETE_SUCCESS = "RESTAURANT_DELETE_SUCCESS";
export const RESTAURANT_DELETE_FAIL = "RESTAURANT_DELETE_FAIL";

export const RESTAURANT_UPDATE_REQUEST = "RESTAURANT_UPDATE_REQUEST";
export const RESTAURANT_UPDATE_SUCCESS = "RESTAURANT_UPDATE_SUCCESS";
export const RESTAURANT_UPDATE_FAIL = "RESTAURANT_UPDATE_FAIL";

export const RESTAURANT_FOODS_REQUEST = "RESTAURANT_FOODS_REQUEST";
export const RESTAURANT_FOODS_SUCCESS = "RESTAURANT_FOODS_SUCCESS";
export const RESTAURANT_FOODS_FAIL = "RESTAURANT_FOODS_FAIL";

export const RESTAURANT_DETAILS_REQUEST = "RESTAURANT_DETAILS_REQUEST";
export const RESTAURANT_DETAILS_SUCCESS = "RESTAURANT_DETAILS_SUCCESS";
export const RESTAURANT_DETAILS_FAIL = "RESTAURANT_DETAILS_FAIL";
