export const SOCIAL_LINKS_REQUEST = "SOCIAL_LINKS_REQUEST";
export const SOCIAL_LINKS_SUCCESS = "SOCIAL_LINKS_SUCCESS";
export const SOCIAL_LINKS_FAIL = "SOCIAL_LINKS_FAIL";

export const SOCIAL_LINKS_UPDATE_REQUEST = "SOCIAL_LINKS_UPDATE_REQUEST";
export const SOCIAL_LINKS_UPDATE_SUCCESS = "SOCIAL_LINKS_UPDATE_SUCCESS";
export const SOCIAL_LINKS_UPDATE_FAIL = "SOCIAL_LINKS_UPDATE_FAIL";
