export const WRITING_LIST_REQUEST = "WRITING_LIST_REQUEST";
export const WRITING_LIST_SUCCESS = "WRITING_LIST_SUCCESS";
export const WRITING_LIST_FAIL = "WRITING_LIST_FAIL";

export const WRITING_ADD_REQUEST = "WRITING_ADD_REQUEST";
export const WRITING_ADD_SUCCESS = "WRITING_ADD_SUCCESS";
export const WRITING_ADD_FAIL = "WRITING_ADD_FAIL";

export const WRITING_DELETE_REQUEST = "WRITING_DELETE_REQUEST";
export const WRITING_DELETE_SUCCESS = "WRITING_DELETE_SUCCESS";
export const WRITING_DELETE_FAIL = "WRITING_DELETE_FAIL";

export const WRITING_UPDATE_REQUEST = "WRITING_UPDATE_REQUEST";
export const WRITING_UPDATE_SUCCESS = "WRITING_UPDATE_SUCCESS";
export const WRITING_UPDATE_FAIL = "WRITING_UPDATE_FAIL";

export const WRITING_DETAILS_REQUEST = "WRITING_DETAILS_REQUEST";
export const WRITING_DETAILS_SUCCESS = "WRITING_DETAILS_SUCCESS";
export const WRITING_DETAILS_FAIL = "WRITING_DETAILS_FAIL";
